name: deploying Hexo project to GitHub pages
on:
  push:
    branches:
      - main # main 分支有 push 行为时就触发这个 action
    workflow_dispatch: 
  #123
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '12' # 建议与你本地开发环境版本一致
      
      - run: npm install -g hexo-cli       # 全局安装 Hexo CLI

      - name: Cache node modules
        uses: actions/cache@v3
      
      - name: Install dependencies
        run: npm install             # 安装依赖
      
      - name: Generate Hexo site
        run: npx hexo clean && npx hexo generate

      - name: Build and Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master
          force_orphan: false
      
