name: deploying Hexo project to GitHub pages
on:
  push:
    branches:
      - raw # master 分支有 push 行为时就触发这个 action
  #123
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build and Deploy
        uses: theme-keep/hexo-deploy-github-pages-action@master
        env:
          PERSONAL_TOKEN: ${{ secrets.GH_DEPLOY_KEY }}
          PUBLISH_REPOSITORY: JamesxuWang/JamesxuWang.github.io
          BRANCH: master
          PUBLISH_DIR: ./public # 部署 public 目录下的文件