name: Build and Update Github Pages

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Build and Deploy
        uses: theme-keep/hexo-deploy-github-pages-action@master
        env:
          PERSONAL_TOKEN: ${{ secrets.GH_DEPLOY_KEY }}
          PUBLISH_REPOSITORY: JamesxuWang/JamesxuWang.github.io
          BRANCH: master
          PUBLISH_DIR: ./public # 部署 public 目录下的文件
          
       
